### PR TITLE
Responsive cascade

### PR DESCRIPTION
**Pull request by chaitanya4vedi**
Fixed #.
While exploring the project i found a few bugs but that wasn't really related to the task so is left as it is. The App was almost fully responsive already. So no changes are made to the part that seem OK. Also the project made use of a framework `sementic-ui` and i used `bootstrap` to make it responsive and mobile friendly. So i carefully implemented only the requried part without letting it interfere with the `sementic-ui` implementation.
#### Changes proposed in the pull request:
- Navigation bar and people page is made fully responsive and mobile friendly
- 
- 

#### Risk Impact
- 

@mohammed786

### CODE REVIEW

**Comment by mohammed786** [comment]
Hey @chaitanya4vedi ,
Thanks for contributing
Can you please add the screenshot of the new ui so that i can have a look at it once.

**Comment by chaitanya4vedi** [comment]
Sure


LoginRadius_FullView
LoginRadius_MobileView
LoginRadius_MobileViewNav

**Comment by mohammed786** [comment]
Thanks for contributing, merging your PR.

**Comment by mohammed786** [comment]
LGTM thanks !

**Pull request merged**
